export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const ONGOING_EVENTS_SUCCESS = "ONGOING_EVENTS_SUCCESS";
export const ALL_EVENTS_SUCCESS = "ALL_EVENTS_SUCCESS";
export const EVENT_DETAIL_SUCCESS = "EVENT_DETAIL_SUCCESS";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const SIGNOUT = "SIGNOUT";
